### ISSUE TITLE
数据集预处理

### ISSUE THREAD

**Issue by qwer902** [HuQ1an/GELIN_TGRS#2]
您好，请问是否可以分享一下数据集处理的代码

**Comment by Baisonm-Li** [comment]
为啥单图超分的模型要使用lms

**Comment by HuQ1an** [comment]
@qwer902  您好，数据集处理的代码我们没有保存，只涉及简单的裁剪以及归一化操作，您可以根据自己的需求写一个

**Comment by HuQ1an** [comment]
@Baisonm-Li lms是LR-HSI使用插值上采样得到结果，超分网络通常使用这个粗糙的上采样结果结合残差连接来传递低频信息
